import Link from 'next/link';
import {ArrowRight,CheckCircle2,Clock3,ShieldCheck,Users} from 'lucide-react';
import ProjectCard from '@/components/ProjectCard';
import SectionTitle from '@/components/SectionTitle';
import {getProjects} from '@/lib/projects';
import {getSiteSettings} from '@/lib/settings';
export default async function Home(){const [projects,settings]=await Promise.all([getProjects(),getSiteSettings()]);return <>
<section className="relative min-h-[650px] overflow-hidden bg-[#081a2c] text-white"><img src={settings.homeHeroImage||"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=2000&q=85"} className="absolute inset-0 h-full w-full object-cover" alt="Modern house"/><div className="hero-overlay absolute inset-0"/><div className="container relative flex min-h-[650px] items-center"><div className="max-w-2xl"><div className="eyebrow text-[#65b2ff]">Construction • Architecture • 3D Design</div><h1 className="mt-4 text-5xl font-black leading-[.98] tracking-[-.05em] md:text-7xl">Building Your Vision Into Reality.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-200">Explore our construction projects, architectural concepts and immersive 3D designs.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/projects" className="btn btn-primary">View Our Projects <ArrowRight size={17}/></Link><Link href="/booking" className="btn border border-white/30 bg-white/10 text-white">Book an Appointment</Link></div></div></div></section>
<section className="section"><div className="container"><div className="mb-10 flex items-end justify-between gap-5"><SectionTitle eyebrow="Portfolio" title="Featured Projects" text="A selection of residential and commercial work."/><Link href="/projects" className="hidden font-bold text-[#147ee8] md:block">View all projects →</Link></div><div className="grid gap-6 md:grid-cols-3">{projects.slice(0,3).map(p=><ProjectCard key={p.slug} project={p}/>)}</div></div></section>
<section className="bg-[#f4f7fb] py-20"><div className="container"><SectionTitle eyebrow="Why BuildVision" title="Built around quality, clarity and delivery." center/><div className="mt-10 grid gap-5 md:grid-cols-4">{[[ShieldCheck,'Quality Construction','Detailed planning and quality-focused delivery.'],[Clock3,'On-Time Delivery','Clear milestones and transparent communication.'],[Users,'Professional Team','Experienced specialists working together.'],[CheckCircle2,'Modern Designs','Practical spaces with contemporary aesthetics.']].map(([Icon,t,d]:any)=><div className="card p-6" key={t}><Icon className="text-[#147ee8]"/><h3 className="mt-5 font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div></div></section>
<section className="section"><div className="container rounded-3xl bg-[#081a2c] p-9 text-white md:p-14"><div className="max-w-2xl"><div className="eyebrow text-[#55a9ff]">Start your project</div><h2 className="mt-3 text-4xl font-black tracking-tight">Let’s build something great together.</h2><p className="mt-4 leading-7 text-slate-300">Tell us what you are planning and book a consultation with our team.</p><Link href="/booking" className="btn btn-primary mt-7">Book a Consultation</Link></div></div></section>
</>}
